# Generated by Django 5.2.8 on 2025-11-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, help_text="A short headline like 'Frontend Developer' or 'Recent Computer Science Graduate'", max_length=150, null=True),
        ),
    ]
