# Generated by Django 5.2.8 on 2025-11-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_education_workexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='user',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
